(()=>{
  const $=id=>document.getElementById(id),lab=$('sshLab'),steps=[...document.querySelectorAll('.lab-step')];let current=0;
  function show(n){current=n;steps.forEach(s=>s.classList.toggle('active',+s.dataset.step===n));document.querySelectorAll('[data-progress]').forEach(x=>{const i=+x.dataset.progress;x.classList.toggle('active',i===n);x.classList.toggle('done',i<n)});document.querySelector('.lab-stage').scrollTop=0;const id={0:'addressInput',1:'keyCommand',2:'publicKey',3:'privateKey',4:'connectCommand'}[n];if(id)setTimeout(()=>$(id).focus(),120)}
  function fallback(text){const a=document.createElement('textarea');a.value=text;a.style.position='fixed';a.style.opacity=0;document.body.append(a);a.select();document.execCommand('copy');a.remove()}
  function copy(id,state){const text=$(id).textContent,done=()=>$(state).textContent='✓ コピーしました';if(navigator.clipboard&&isSecureContext)navigator.clipboard.writeText(text).then(done).catch(()=>{fallback(text);done()});else{fallback(text);done()}}
  function reset(){['addressInput','keyCommand','serverTextarea','connectCommand'].forEach(id=>$(id).value='');$('publicCode').classList.remove('show');$('serverWindow').classList.remove('show');$('serverSuccess').classList.remove('show');$('vaultSuccess').classList.remove('show');$('connectedServer').classList.remove('connected');$('serverLabel').textContent='未接続';$('keyOutput').textContent='コマンドを入力して Enter。';$('connectOutput').textContent='秘密鍵を指定して接続します。';$('dropHint').hidden=false;$('privateKey').draggable=true;show(0)}
  $('openLab').onclick=()=>{lab.showModal();show(0)};$('closeLab').onclick=()=>lab.close();lab.onclick=e=>{if(e.target===lab)lab.close()};$('resetLab').onclick=reset;
  $('addressInput').onkeydown=e=>{if(e.key!=='Enter')return;e.preventDefault();if(e.target.value.trim().toLowerCase()==='cmd'){$('status0').textContent='✓ コマンドプロンプトを開きます。';setTimeout(()=>show(1),600)}else $('status0').textContent='「cmd」と入力してください。'};
  $('keyCommand').onkeydown=e=>{if(e.key!=='Enter')return;e.preventDefault();if(e.target.value.trim().replace(/\s+/g,' ')==='ssh-keygen -t ed25519'){$('keyOutput').textContent='Generating public/private ed25519 key pair.\nYour identification has been saved in C:\\Users\\あなた\\.ssh\\id_ed25519\nYour public key has been saved in C:\\Users\\あなた\\.ssh\\id_ed25519.pub\n✓ 鍵ペアを生成しました。';setTimeout(()=>show(2),1400)}else{$('keyOutput').textContent='入力を確認： ssh-keygen -t ed25519';$('keyOutput').classList.add('error')}};
  $('publicKey').onclick=()=>{$('publicCode').classList.add('show');$('publicKey').classList.remove('highlight');$('copyKey').classList.add('highlight')};$('copyKey').onclick=()=>{copy('publicKeyText','copyMessage');$('copyKey').classList.remove('highlight');$('serverCard').classList.add('highlight')};$('serverCard').onclick=()=>{$('serverWindow').classList.add('show');$('serverCard').classList.remove('highlight');setTimeout(()=>$('serverTextarea').focus(),100)};$('registerKey').onclick=()=>{if(!$('serverTextarea').value.trim().startsWith('ssh-ed25519 ')){$('guide2').innerHTML='<b>公開鍵がありません。</b> ssh-ed25519から始まる文字列を貼り付けてください。';return}$('serverSuccess').classList.add('show');setTimeout(()=>show(3),800)};
  const key=$('privateKey'),drop=$('vaultDrop');function stored(){$('vaultSuccess').classList.add('show');$('dropHint').hidden=true;key.draggable=false;setTimeout(()=>show(4),1200)}key.ondragstart=e=>e.dataTransfer.setData('text/plain','key');drop.ondragover=e=>e.preventDefault();drop.ondrop=e=>{e.preventDefault();stored()};key.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();stored()}};let start;key.onpointerdown=e=>{start=[e.clientX,e.clientY];key.setPointerCapture(e.pointerId)};key.onpointerup=e=>{if(start&&Math.hypot(e.clientX-start[0],e.clientY-start[1])>15)stored();start=null};
  $('connectCommand').onkeydown=e=>{if(e.key!=='Enter')return;e.preventDefault();if(/^ssh\s+-i\s+.+\s+[^\s@]+@[^\s@]+$/i.test(e.target.value.trim())){$('connectOutput').textContent='Authenticated with public key.\nWelcome to FreeBSD!\n✓ パスワードを送らずに接続しました。';$('connectedServer').classList.add('connected');$('serverLabel').textContent='接続成功';setTimeout(()=>show(5),1700)}else{$('connectOutput').textContent='ssh -i 秘密鍵のパス ユーザー名@ホスト名 の形で入力してください。';$('connectOutput').classList.add('error')}};
  document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copy(b.dataset.copy,b.dataset.copy==='pagePrompt'?'pagePromptState':'labPromptState'));const top=$('toTop');onscroll=()=>top.classList.toggle('show',scrollY>360);top.onclick=()=>scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'});const ob=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>ob.observe(e));show(0);
})();
